-- 合作平台
UPDATE `report`.`report_resource_column` SET `id`='14', `querySql`='SELECT b.agency_no AS \'code\', \r\n			COUNT(1) AS \'num\'\r\nFROM (\r\n	  SELECT\r\n			q.agency_no,\r\n			q.cust_id\r\n		FROM\r\n			osdc.osdc_static_quty q\r\n		WHERE\r\n			q.agency_no in (codes)\r\n		GROUP BY\r\n			q.agency_no, q.cust_id\r\n		HAVING\r\n			SUM(q.quty_balance) > 0\r\n) b GROUP BY b.agency_no;' WHERE (`id`='14');
UPDATE `report`.`report_resource_column` SET `id`='17', `querySql`='SELECT q.agency_no AS \'code\',\r\n		SUM(q.confirm_balance / 100) AS \'num\'\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no in (codes) \r\nAND q.confirm_date <= \'dataDate\'\r\nAND q.busi_code in (\'120\',\'122\',\'139\')\r\nGROUP BY	q.agency_no' WHERE (`id`='17');
UPDATE `report`.`report_resource_column` SET `id`='18', `querySql`='SELECT q.agency_no AS \'code\',\r\n			SUM(q.quty_balance * i.nav /100) AS \'num\'\r\nFROM (\r\n	SELECT\r\n			q.agency_no,q.quty_balance,q.fund_code\r\n		FROM\r\n			osdc.osdc_static_quty q\r\n    WHERE\r\n			q.agency_no in (codes)\r\n) q JOIN (\r\n	 select t2.fund_id as fund_id, t2.nav as nav from\r\n	 (\r\n			select fund_id , max(nav_date) max_nav_date from osdc.osdc_net_info t group by fund_id\r\n	 ) t1, osdc.osdc_net_info t2\r\n	 where t1.fund_id = t2.fund_id\r\n	 and t2.nav_date = t1.max_nav_date\r\n) i ON q.fund_code = i.fund_id\r\nGROUP BY q.agency_no;' WHERE (`id`='18');
UPDATE `report`.`report_resource_column` SET `id`='19', `querySql`='SELECT q.agency_no AS \'code\',\r\n		SUM(q.confirm_balance / 100) AS \'num\'\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no in (codes) \r\nAND q.confirm_date = \'dataDate\'\r\nAND q.busi_code in (\'120\',\'122\',\'139\')\r\nGROUP BY	q.agency_no;' WHERE (`id`='19');
UPDATE `report`.`report_resource_column` SET `id`='20', `querySql`='SELECT COUNT(1) \r\nFROM (\r\n  SELECT DISTINCT q.cust_id AS \'num\'\r\n	FROM	osdc.osdc_trade_confirm q \r\n	WHERE	 q.agency_no = \'260\'\r\n	AND q.confirm_date <= \'dataDate\'\r\n	AND q.busi_code in (\'120\',\'122\',\'139\')\r\n	AND q.cust_id IN (\r\n		SELECT DISTINCT i.cust_id FROM osdc.osdc_trade_acct_info i WHERE i.agency_no = \'260\' AND i.net_no = \'26001\'\r\n	)\r\n	GROUP BY	q.agency_no,q.cust_id\r\n)b;' WHERE (`id`='20');
UPDATE `report`.`report_resource_column` SET `id`='24', `querySql`='SELECT SUM(q.confirm_balance / 100) AS \'num\'\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'260\'\r\nAND q.confirm_date <= \'dataDate\'\r\nAND q.busi_code in (\'120\',\'122\',\'139\')\r\nAND q.cust_id IN (\r\n	SELECT DISTINCT i.cust_id FROM osdc.osdc_trade_acct_info i WHERE i.agency_no = \'260\' AND i.net_no = \'26001\'\r\n)\r\nGROUP BY	q.agency_no;' WHERE (`id`='24');
UPDATE `report`.`report_resource_column` SET `id`='25', `querySql`='SELECT SUM(q.quty_balance * i.nav / 100) AS \'num\'\r\nFROM (\r\n	SELECT\r\n			q.agency_no,q.quty_balance,q.fund_code\r\n		FROM\r\n			osdc.osdc_static_quty q,\r\n			osdc.osdc_trade_acct_info i\r\n		WHERE\r\n			q.fund_acct = i.fund_acct\r\n		AND q.trade_acct = i.trade_acct\r\n		AND q.cust_id = i.cust_id\r\n		AND i.agency_no = \'260\'\r\n		AND i.net_no = \'26001\'\r\n) q JOIN (\r\n	 select t2.fund_id as fund_id, t2.nav as nav from\r\n	 (\r\n			select fund_id , max(nav_date) max_nav_date from osdc.osdc_net_info t group by fund_id\r\n	 ) t1,osdc.osdc_net_info t2\r\n	 where t1.fund_id = t2.fund_id\r\n	 and t2.nav_date = t1.max_nav_date\r\n) i ON q.fund_code = i.fund_id\r\nGROUP BY q.agency_no;' WHERE (`id`='25');
UPDATE `report`.`report_resource_column` SET `id`='26', `querySql`='SELECT SUM(q.confirm_balance /100) AS \'num\'\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'260\'\r\nAND q.confirm_date = \'dataDate\'\r\nAND q.busi_code in (\'120\',\'122\',\'139\')\r\nAND q.cust_id IN (\r\n	SELECT DISTINCT i.cust_id FROM osdc.osdc_trade_acct_info i WHERE i.agency_no = \'260\' AND i.net_no = \'26001\'\r\n)\r\nGROUP BY	q.agency_no' WHERE (`id`='26');
UPDATE `report`.`report_resource_column` SET `id`='28', `querySql`='SELECT COUNT(1) AS \'num\' \r\nFROM (\r\n	SELECT\r\n			q.cust_id\r\n		FROM\r\n			osdc.osdc_static_quty q\r\n		WHERE\r\n			q.agency_no = \'469\' AND q.net_no = \'0002\'\r\n		GROUP BY\r\n			q.cust_id\r\n		HAVING\r\n			SUM(q.quty_balance) > 0\r\n) b' WHERE (`id`='28');
UPDATE `report`.`report_resource_column` SET `id`='29', `querySql`='SELECT COUNT(1) FROM (\r\n	SELECT\r\n			COUNT(q.cust_id)\r\n		FROM\r\n			osdc.osdc_static_quty q\r\n		WHERE\r\n			q.agency_no = \'469\' AND q.net_no = \'0002\'\r\n		GROUP BY\r\n			 q.cust_id\r\n		HAVING\r\n			SUM(q.quty_balance) = 0\r\n) b;' WHERE (`id`='29');
UPDATE `report`.`report_resource_column` SET `id`='30', `querySql`='SELECT COUNT(DISTINCT q.cust_id)\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'469\' AND q.net_no = \'0002\'\r\nAND q.confirm_date = \'dataDate\'\r\nAND q.busi_code in (\'120\',\'122\',\'139\')\r\nGROUP BY	q.agency_no' WHERE (`id`='30');
UPDATE `report`.`report_resource_column` SET `id`='31', `querySql`='SELECT q.agency_no AS \'code\',\r\n		SUM(q.confirm_balance /100) AS \'num\'\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'469\' AND q.net_no = \'0002\'\r\nAND q.confirm_date <= \'dataDate\'\r\nAND q.busi_code in (\'120\',\'122\',\'139\')\r\nGROUP BY	q.agency_no	;' WHERE (`id`='31');
UPDATE `report`.`report_resource_column` SET `id`='32', `querySql`='SELECT SUM(q.quty_balance * i.nav / 100) AS \'num\'\r\nFROM (\r\n	SELECT\r\n			q.agency_no,q.quty_balance,q.fund_code\r\n		FROM\r\n			osdc.osdc_static_quty q\r\n		WHERE\r\n			q.agency_no = \'469\' AND q.net_no = \'0002\'\r\n) q JOIN (\r\n	 select t2.fund_id as fund_id, t2.nav as nav from\r\n	 (\r\n			select fund_id , max(nav_date) max_nav_date from osdc.osdc_net_info t group by fund_id\r\n	 ) t1,osdc.osdc_net_info t2\r\n	 where t1.fund_id = t2.fund_id\r\n	 and t2.nav_date = t1.max_nav_date\r\n) i ON q.fund_code = i.fund_id' WHERE (`id`='32');

-- 滚钱宝 -- 钱滚滚直销

UPDATE `report`.`report_resource_column` SET `id`='48', `querySql`='SELECT\r\n	SUM(o.amount /100)\r\nFROM\r\n	transcore.tcs_order o\r\nJOIN transcore.tcs_order_pay p ON o.id = p.order_id\r\nJOIN transcore.tcs_order_pay_detail d ON p.id = d.order_pay_id\r\nAND p.latest_status = \'S\'\r\nAND d.pay_tool IN (\'11\', \"12\")\r\nAND o.sub_trans_code = \'1201\'\r\nAND o.product_id = \'600001\'\r\nAND d.bank_date <= \'dataDate\';' WHERE (`id`='48');
UPDATE `report`.`report_resource_column` SET `id`='49', `querySql`='SELECT\r\n	SUM(o.amount /100)\r\nFROM\r\n	transcore.tcs_order o\r\nJOIN transcore.tcs_order_pay p ON o.id = p.order_id\r\nJOIN transcore.tcs_order_pay_detail d ON p.id = d.order_pay_id\r\nAND p.latest_status = \'S\'\r\nAND d.pay_tool IN (\'11\', \"12\")\r\nAND o.sub_trans_code = \'1201\'\r\nAND o.product_id = \'600001\'\r\nAND d.bank_date <= \'dataDate\';' WHERE (`id`='49');
UPDATE `report`.`report_resource_column` SET `id`='51', `querySql`='SELECT\r\n	SUM(fb.quty_balance / 100)\r\nFROM\r\n	merchant.mht_user_fund_quty_balance fb\r\nWHERE\r\n	fb.quty_balance > 0\r\nAND (fb.quty_status IS NULL OR fb.quty_status != \'D\')\r\nAND fb.product_id = \'600001\';' WHERE (`id`='51');
UPDATE `report`.`report_resource_column` SET `id`='52', `querySql`='SELECT\r\n	SUM(o.amount /100)\r\nFROM\r\n	transcore.tcs_order o\r\nJOIN transcore.tcs_order_pay p ON o.id = p.order_id\r\nJOIN transcore.tcs_order_pay_detail d ON p.id = d.order_pay_id\r\nAND p.latest_status = \'S\'\r\nAND d.pay_tool IN (\'11\', \"12\")\r\nAND o.sub_trans_code IN (\'0101\',\'0103\')\r\nAND o.product_id = \'600001\'\r\nAND d.bank_date = \'dataDate\';' WHERE (`id`='52');
UPDATE `report`.`report_resource_column` SET `id`='53', `querySql`='SELECT\r\n	SUM(o.amount / 100)\r\nFROM\r\n	transcore.tcs_order o\r\nJOIN transcore.tcs_order_pay p ON o.id = p.order_id\r\nJOIN transcore.tcs_order_pay_detail d ON p.id = d.order_pay_id\r\nAND p.latest_status = \'S\'\r\nAND d.pay_tool IN (\'11\', \"12\")\r\nAND o.sub_trans_code = \'1201\'\r\nAND o.product_id = \'600001\'\r\nAND d.bank_date = \'dataDate\';' WHERE (`id`='53');
UPDATE `report`.`report_resource_column` SET `id`='54', `querySql`='SELECT\r\n	SUM(o.amount /100)\r\nFROM\r\n	transcore.tcs_order o\r\nWHERE o.sub_trans_code IN (\'0301\',\'0302\',\'0302\')\r\nAND o.product_id = \'600001\'\r\nAND o.latest_status IN (\'TI\',\'TP\',\'TY\',\'TF\',\'Y\',\'YP\',\'F\')\r\nAND o.apply_date = \'dataDate\';' WHERE (`id`='54');

-- 滚钱宝 -- 如意宝直销
UPDATE `report`.`report_resource_column` SET `id`='63', `querySql`='SELECT SUM(q.apply_balance / 100)\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'469\' AND q.net_no = \'0002\'\r\nAND q.confirm_date <= \'dataDate\'\r\nAND q.fund_code = \'001211\'\r\nAND q.busi_code = \'122\';' WHERE (`id`='63');
UPDATE `report`.`report_resource_column` SET `id`='65', `querySql`='NONE' WHERE (`id`='65');
UPDATE `report`.`report_resource_column` SET `id`='66', `querySql`='SELECT\r\n	SUM(q.quty_balance / 100)\r\nFROM\r\n	osdc.osdc_static_quty q\r\nWHERE\r\n	q.agency_no = \'469\' \r\nAND q.net_no = \'0002\'\r\nAND q.fund_code = \'001211\'' WHERE (`id`='66');
UPDATE `report`.`report_resource_column` SET `id`='67', `querySql`='SELECT SUM(q.confirm_balance /100)\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'469\' AND q.net_no = \'0002\'\r\nAND q.confirm_date = \"dataDate\"\r\nAND q.fund_code = \'001211\'\r\nAND q.busi_code in (\'122\')' WHERE (`id`='67');
UPDATE `report`.`report_resource_column` SET `id`='69', `querySql`='SELECT SUM(q.confirm_balance /100)\r\nFROM	osdc.osdc_trade_confirm q\r\nWHERE	 q.agency_no = \'469\' AND q.net_no = \'0002\'\r\nAND q.confirm_date = \"dataDate\"\r\nAND q.fund_code = \'001211\'\r\nAND q.busi_code in (\'124\')' WHERE (`id`='69');


-- 基金

-- 组合
UPDATE `report`.`report_resource_column` SET `id`='119', `querySql`='SELECT\r\n	fb.fof_id AS \'code\', \r\n  COUNT(DISTINCT fb.asset_acct_id) AS \'num\'\r\nFROM\r\n	merchant.mht_user_fund_quty_balance fb\r\nWHERE\r\n	fb.quty_balance > 0\r\nAND (fb.quty_status IS NULL OR fb.quty_status != \'D\')\r\nAND fb.fof_id in (codes)\r\nGROUP BY fb.product_id;' WHERE (`id`='119');
UPDATE `report`.`report_resource_column` SET `id`='125', `querySql`='SELECT\r\n	fb.fof_id AS \'code\', SUM(fb.quty_balance * p.nav / 100) AS \'num\'\r\nFROM\r\n	merchant.mht_user_fund_quty_balance fb JOIN ( SELECT id, IFNULL(nav, \'1\') AS nav FROM product.pcs_product p ) p ON fb.product_id = p.id\r\nAND	fb.quty_balance > 0\r\nAND (fb.quty_status IS NULL OR fb.quty_status != \'D\')\r\nAND fb.fof_id in (codes)\r\nGROUP BY fb.product_id;' WHERE (`id`='125');
UPDATE `report`.`report_resource_column` SET `id`='126', `querySql`='SELECT\r\n	fb.fof_id AS \'code\', SUM(fb.quty_balance) AS \'num\'\r\nFROM\r\n	merchant.mht_user_fund_quty_balance fb\r\nWHERE\r\n	fb.quty_balance > 0\r\nAND (fb.quty_status IS NULL OR fb.quty_status != \'D\')\r\nAND fb.fof_id in (codes)\r\nGROUP BY fb.product_id;' WHERE (`id`='126');

-- 收益凭证
UPDATE `report`.`report_resource_column` SET `id`='154', `querySql`='SELECT\r\n	o.product_id AS \'code\', \r\n  SUM(o.amount /100) AS \'num\'\r\nFROM\r\n	transcore.tcs_order o\r\nJOIN transcore.tcs_order_pay p ON o.id = p.order_id\r\nJOIN transcore.tcs_order_pay_detail d ON p.id = d.order_pay_id\r\nAND p.latest_status = \'S\'\r\nAND d.pay_tool IN (\'11\', \"12\")\r\nAND o.sub_trans_code IN (\'0201\',\'0202\')\r\nAND o.product_id in (codes)\r\nAND d.bank_date <= \'dataDate\'\r\nGROUP BY o.product_id;' WHERE (`id`='154');

